name: Test phython env in github
on: [push]
jobs:
  detect-secrets:
    runs-on: ubuntu-latest
  
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Ser python env
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
      
    - name: Install git-secret packages
      run: |
        python -m pip3 install --upgrade pip3
        pip3 install pre-commit
        echo "repos:
            - repo: https://github.com/Yelp/detect-secrets
              rev: v1.3.0
              hooks:
              - id: detect-secrets" > .pre-commit-config.yaml
        echo "### pre-commit-config.yaml data"
        cat .pre-commit-config.yaml
      
        pre-commit install pre-commit        
        pre-commit install pre-push
      
        ls -ltr .git/hooks/
      
